# Overview

This resource outlines the structure and content of our level 1 practical course at the School of Psychology at the University of Glasgow. We have developed these with a few key principles in mind:

1. Pre, in-class and assessment. Each practical class, which we call labs in the student's timetable and in this book, has prep material for the students to read and work through to provide context and additional support before the students attend class and work on the the in-class activites. These can take the form of, for example, videos made by the course lead informally talking through the tasks while live coding, papers related to the data being used, lectures related to the topic of the lab. These prep and in-class activities are closely linked to the assessments to enable skills to develop through practice. We also hold drop in practice sessions twice a week where Graduate Teaching Assistants (GTAs) are present to guide students to prep and in-class activites that will help in assessment completion while taking a hands-off the keyboard approach.   

2. The assessment enables the students to demonstrate their competency of the skills learnt in class. However, we take the perspective of skills develop through practice therefore each assessment builds on the work not only completed in the associated lab but provides an opportunity to demomstrate skill acquisition of skills learnt to date over the previous labs. Students will have received the solution for the previously attempted lab as a minimum, grade and feedback as well as the solution if feedback and grade turnaround permits, so this is an excellent opportunity for them to demonstrate integration of feedback and related skill development.

3. Live coding is an important part of our teaching. We structure our classes with a staff member leading with support from two Graduate Teaching Assistants (GTAs). This enables the staff member to lead the class through the content while the GTAs can ensure the individual students are being challenged and supported adequately. The structure of skill building over labs supports this mode of teaching with the focus being on what each component of the code enables us to do rather than memorising code. Additional lab activites, such as the building of a portfolio over each semester, aims to encourage our students to focus on the understanding of the aim of the task the obtaining the code rather than memorising code only. 

# The overall goal for our students in our year 1 Psychology labs

* To understand the current state of psychological science and what Open Science is as well as its importance

* To be clear on the importance of being confident and competent in data management 
* To be confident and competent at using RStudio as a tool to acheive good data management skills 


