<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>5 Data wrangling 1 | Level 1 Data Skills</title>
  <meta name="description" content="ug1-practical-materials" />
  <meta name="generator" content="bookdown 0.20 and GitBook 2.6.7" />

  <meta property="og:title" content="5 Data wrangling 1 | Level 1 Data Skills" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="ug1-practical-materials" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="5 Data wrangling 1 | Level 1 Data Skills" />
  
  <meta name="twitter:description" content="ug1-practical-materials" />
  




  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="loading-data.html"/>
<link rel="next" href="data-wrangling-2.html"/>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<script src="libs/accessible-code-block-0.0.1/empty-anchor.js"></script>
<link href="libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0/anchor-sections.js"></script>


<style type="text/css">
code.sourceCode > span { display: inline-block; line-height: 1.25; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="include/psyteachr.css" type="text/css" />
<link rel="stylesheet" href="include/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Level 1 Data Skills</a></li>
<li><a href="https://doi.org/10.5281/zenodo.3966961"><img src="https://zenodo.org/badge/DOI/10.5281/zenodo.3966961.svg" alt="DOI"></a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Course Information</a></li>
<li class="chapter" data-level="1" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html"><i class="fa fa-check"></i><b>1</b> Getting to know the data</a><ul>
<li class="chapter" data-level="1.1" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html#activity-1"><i class="fa fa-check"></i><b>1.1</b> Activity 1</a></li>
<li class="chapter" data-level="1.2" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html#activity-2"><i class="fa fa-check"></i><b>1.2</b> Activity 2</a></li>
<li class="chapter" data-level="1.3" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html#activity-3"><i class="fa fa-check"></i><b>1.3</b> Activity 3</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="programming-basics.html"><a href="programming-basics.html"><i class="fa fa-check"></i><b>2</b> Programming basics</a><ul>
<li class="chapter" data-level="2.0.1" data-path="programming-basics.html"><a href="programming-basics.html#r-and-r-studio"><i class="fa fa-check"></i><b>2.0.1</b> R and R Studio</a></li>
<li class="chapter" data-level="2.0.2" data-path="programming-basics.html"><a href="programming-basics.html#how-to-use-r-and-r-studio"><i class="fa fa-check"></i><b>2.0.2</b> How to use R and R Studio</a></li>
<li class="chapter" data-level="2.0.3" data-path="programming-basics.html"><a href="programming-basics.html#r-server"><i class="fa fa-check"></i><b>2.0.3</b> R server</a></li>
<li class="chapter" data-level="2.0.4" data-path="programming-basics.html"><a href="programming-basics.html#installing-r-on-your-computer"><i class="fa fa-check"></i><b>2.0.4</b> Installing R on your computer</a></li>
<li class="chapter" data-level="2.0.5" data-path="programming-basics.html"><a href="programming-basics.html#getting-to-know-r-studio"><i class="fa fa-check"></i><b>2.0.5</b> Getting to know R Studio</a></li>
<li class="chapter" data-level="2.0.6" data-path="programming-basics.html"><a href="programming-basics.html#console-vs.-scripts"><i class="fa fa-check"></i><b>2.0.6</b> Console vs. scripts</a></li>
<li class="chapter" data-level="2.0.7" data-path="programming-basics.html"><a href="programming-basics.html#functions-and-arguments"><i class="fa fa-check"></i><b>2.0.7</b> Functions and arguments</a></li>
<li class="chapter" data-level="2.0.8" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html#activity-1"><i class="fa fa-check"></i><b>2.0.8</b> Activity 1</a></li>
<li class="chapter" data-level="2.0.9" data-path="getting-to-know-the-data.html"><a href="getting-to-know-the-data.html#activity-2"><i class="fa fa-check"></i><b>2.0.9</b> Activity 2</a></li>
<li class="chapter" data-level="2.0.10" data-path="programming-basics.html"><a href="programming-basics.html#argument-names"><i class="fa fa-check"></i><b>2.0.10</b> Argument names</a></li>
<li class="chapter" data-level="2.0.11" data-path="programming-basics.html"><a href="programming-basics.html#tab-auto-complete"><i class="fa fa-check"></i><b>2.0.11</b> Tab auto-complete</a></li>
<li class="chapter" data-level="2.0.12" data-path="programming-basics.html"><a href="programming-basics.html#packages"><i class="fa fa-check"></i><b>2.0.12</b> Base R and packages</a></li>
<li class="chapter" data-level="2.0.13" data-path="programming-basics.html"><a href="programming-basics.html#activity-3-install-the-tidyverse-optional"><i class="fa fa-check"></i><b>2.0.13</b> Activity 3: Install the tidyverse (optional)</a></li>
<li class="chapter" data-level="2.0.14" data-path="programming-basics.html"><a href="programming-basics.html#activity-4-load-the-tidyverse"><i class="fa fa-check"></i><b>2.0.14</b> Activity 4: Load the tidyverse</a></li>
<li class="chapter" data-level="2.0.15" data-path="programming-basics.html"><a href="programming-basics.html#package-updates"><i class="fa fa-check"></i><b>2.0.15</b> Package updates</a></li>
<li class="chapter" data-level="2.0.16" data-path="programming-basics.html"><a href="programming-basics.html#conflicts"><i class="fa fa-check"></i><b>2.0.16</b> Package conflicts</a></li>
<li class="chapter" data-level="2.0.17" data-path="programming-basics.html"><a href="programming-basics.html#objects"><i class="fa fa-check"></i><b>2.0.17</b> Objects</a></li>
<li class="chapter" data-level="2.0.18" data-path="programming-basics.html"><a href="programming-basics.html#activity-5-create-some-objects"><i class="fa fa-check"></i><b>2.0.18</b> Activity 5: Create some objects</a></li>
<li class="chapter" data-level="2.0.19" data-path="programming-basics.html"><a href="programming-basics.html#looking-after-the-environment"><i class="fa fa-check"></i><b>2.0.19</b> Looking after the environment</a></li>
<li class="chapter" data-level="2.0.20" data-path="programming-basics.html"><a href="programming-basics.html#global-options"><i class="fa fa-check"></i><b>2.0.20</b> Global options</a></li>
<li class="chapter" data-level="2.0.21" data-path="programming-basics.html"><a href="programming-basics.html#r-sessions"><i class="fa fa-check"></i><b>2.0.21</b> R sessions</a></li>
<li class="chapter" data-level="2.0.22" data-path="programming-basics.html"><a href="programming-basics.html#help-and-additional-resources"><i class="fa fa-check"></i><b>2.0.22</b> Help and additional resources</a></li>
<li class="chapter" data-level="2.0.23" data-path="programming-basics.html"><a href="programming-basics.html#debugging-tips"><i class="fa fa-check"></i><b>2.0.23</b> Debugging tips</a></li>
<li class="chapter" data-level="2.0.24" data-path="programming-basics.html"><a href="programming-basics.html#activity-6-test-yourself"><i class="fa fa-check"></i><b>2.0.24</b> Activity 6: Test yourself</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="ref1.html"><a href="ref1.html"><i class="fa fa-check"></i><b>3</b> Intro to R</a><ul>
<li class="chapter" data-level="3.0.1" data-path="ref1.html"><a href="ref1.html#activity-1-upload-data-files-to-the-server"><i class="fa fa-check"></i><b>3.0.1</b> Activity 1: Upload data files to the server</a></li>
<li class="chapter" data-level="3.0.2" data-path="ref1.html"><a href="ref1.html#activity-2-set-the-working-directory"><i class="fa fa-check"></i><b>3.0.2</b> Activity 2: Set the working directory</a></li>
<li class="chapter" data-level="3.0.3" data-path="ref1.html"><a href="ref1.html#r-markdown-for-data-skills-work-and-homework-assignments"><i class="fa fa-check"></i><b>3.0.3</b> R Markdown for data skills work and homework assignments</a></li>
<li class="chapter" data-level="3.0.4" data-path="ref1.html"><a href="ref1.html#activity-3-open-and-save-a-new-r-markdown-document"><i class="fa fa-check"></i><b>3.0.4</b> Activity 3: Open and save a new R Markdown document</a></li>
<li class="chapter" data-level="3.0.5" data-path="ref1.html"><a href="ref1.html#activity-4-create-a-new-code-chunk"><i class="fa fa-check"></i><b>3.0.5</b> Activity 4: Create a new code chunk</a></li>
<li class="chapter" data-level="3.0.6" data-path="ref1.html"><a href="ref1.html#activity-5-write-some-code"><i class="fa fa-check"></i><b>3.0.6</b> Activity 5: Write some code</a></li>
<li class="chapter" data-level="3.0.7" data-path="ref1.html"><a href="ref1.html#running-code"><i class="fa fa-check"></i><b>3.0.7</b> Running code</a></li>
<li class="chapter" data-level="3.0.8" data-path="ref1.html"><a href="ref1.html#activity-6-run-your-code"><i class="fa fa-check"></i><b>3.0.8</b> Activity 6: Run your code</a></li>
<li class="chapter" data-level="3.0.9" data-path="ref1.html"><a href="ref1.html#activity-7-inline-code"><i class="fa fa-check"></i><b>3.0.9</b> Activity 7: Inline code</a></li>
<li class="chapter" data-level="3.0.10" data-path="ref1.html"><a href="ref1.html#activity-8-knitting-your-file"><i class="fa fa-check"></i><b>3.0.10</b> Activity 8: Knitting your file</a></li>
<li class="chapter" data-level="3.1" data-path="ref1.html"><a href="ref1.html#activity-9-make-r-your-own"><i class="fa fa-check"></i><b>3.1</b> Activity 9: Make R your own</a><ul>
<li class="chapter" data-level="3.1.1" data-path="ref1.html"><a href="ref1.html#finished"><i class="fa fa-check"></i><b>3.1.1</b> Finished</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="loading-data.html"><a href="loading-data.html"><i class="fa fa-check"></i><b>4</b> Loading data</a><ul>
<li class="chapter" data-level="4.0.1" data-path="loading-data.html"><a href="loading-data.html#getting-data-ready-to-work-with"><i class="fa fa-check"></i><b>4.0.1</b> Getting data ready to work with</a></li>
<li class="chapter" data-level="4.0.2" data-path="loading-data.html"><a href="loading-data.html#stub-files"><i class="fa fa-check"></i><b>4.0.2</b> Stub files</a></li>
<li class="chapter" data-level="4.1" data-path="loading-data.html"><a href="loading-data.html#activity-1-set-up"><i class="fa fa-check"></i><b>4.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="4.2" data-path="loading-data.html"><a href="loading-data.html#activity-2-load-in-the-package"><i class="fa fa-check"></i><b>4.2</b> Activity 2: Load in the package</a></li>
<li class="chapter" data-level="4.3" data-path="loading-data.html"><a href="loading-data.html#open-data"><i class="fa fa-check"></i><b>4.3</b> Open data</a></li>
<li class="chapter" data-level="4.4" data-path="loading-data.html"><a href="loading-data.html#activity-3-read-in-data"><i class="fa fa-check"></i><b>4.4</b> Activity 3: Read in data</a><ul>
<li class="chapter" data-level="4.4.1" data-path="loading-data.html"><a href="loading-data.html#activity-4-check-your-data"><i class="fa fa-check"></i><b>4.4.1</b> Activity 4: Check your data</a></li>
<li class="chapter" data-level="4.4.2" data-path="loading-data.html"><a href="loading-data.html#activity-5-join-the-files-together"><i class="fa fa-check"></i><b>4.4.2</b> Activity 5: Join the files together</a></li>
<li class="chapter" data-level="4.4.3" data-path="loading-data.html"><a href="loading-data.html#activity-6-pull-out-variables-of-interest"><i class="fa fa-check"></i><b>4.4.3</b> Activity 6: Pull out variables of interest</a></li>
<li class="chapter" data-level="4.4.4" data-path="loading-data.html"><a href="loading-data.html#activity-7-visualise-the-data"><i class="fa fa-check"></i><b>4.4.4</b> Activity 7: Visualise the data</a></li>
<li class="chapter" data-level="4.4.5" data-path="programming-basics.html"><a href="programming-basics.html#debugging-tips"><i class="fa fa-check"></i><b>4.4.5</b> Debugging tips</a></li>
<li class="chapter" data-level="4.4.6" data-path="loading-data.html"><a href="loading-data.html#test-yourself"><i class="fa fa-check"></i><b>4.4.6</b> Test yourself</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="5" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html"><i class="fa fa-check"></i><b>5</b> Data wrangling 1</a><ul>
<li class="chapter" data-level="5.1" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#tidyverse"><i class="fa fa-check"></i><b>5.1</b> Tidyverse</a></li>
<li class="chapter" data-level="5.2" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#the-babynames-database"><i class="fa fa-check"></i><b>5.2</b> The <code>babynames</code> database</a></li>
<li class="chapter" data-level="5.3" data-path="loading-data.html"><a href="loading-data.html#activity-1-set-up"><i class="fa fa-check"></i><b>5.3</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="5.4" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-2-look-at-the-data"><i class="fa fa-check"></i><b>5.4</b> Activity 2: Look at the data</a></li>
<li class="chapter" data-level="5.5" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-3-data-visualisation"><i class="fa fa-check"></i><b>5.5</b> Activity 3: Data visualisation</a></li>
<li class="chapter" data-level="5.6" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-4-selecting-variables-of-interest"><i class="fa fa-check"></i><b>5.6</b> Activity 4: Selecting variables of interest</a></li>
<li class="chapter" data-level="5.7" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-5-arranging-the-data"><i class="fa fa-check"></i><b>5.7</b> Activity 5: Arranging the data</a></li>
<li class="chapter" data-level="5.8" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-6-using-filter-to-select-observations"><i class="fa fa-check"></i><b>5.8</b> Activity 6: Using filter to select observations</a></li>
<li class="chapter" data-level="5.9" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-7-creating-new-variables"><i class="fa fa-check"></i><b>5.9</b> Activity 7: Creating new variables</a></li>
<li class="chapter" data-level="5.10" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-8-grouping-and-summarising"><i class="fa fa-check"></i><b>5.10</b> Activity 8: Grouping and summarising</a></li>
<li class="chapter" data-level="5.11" data-path="data-wrangling-1.html"><a href="data-wrangling-1.html#activity-9-pipes"><i class="fa fa-check"></i><b>5.11</b> Activity 9: Pipes</a></li>
<li class="chapter" data-level="5.12" data-path="ref1.html"><a href="ref1.html#finished"><i class="fa fa-check"></i><b>5.12</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html"><i class="fa fa-check"></i><b>6</b> Data wrangling 2</a><ul>
<li class="chapter" data-level="6.1" data-path="loading-data.html"><a href="loading-data.html#activity-1-set-up"><i class="fa fa-check"></i><b>6.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="6.2" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-2-select"><i class="fa fa-check"></i><b>6.2</b> Activity 2: Select</a></li>
<li class="chapter" data-level="6.3" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-3-arrange"><i class="fa fa-check"></i><b>6.3</b> Activity 3: Arrange</a></li>
<li class="chapter" data-level="6.4" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-4-filter"><i class="fa fa-check"></i><b>6.4</b> Activity 4: Filter</a></li>
<li class="chapter" data-level="6.5" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-5-summarise"><i class="fa fa-check"></i><b>6.5</b> Activity 5: Summarise</a></li>
<li class="chapter" data-level="6.6" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-6-group_by"><i class="fa fa-check"></i><b>6.6</b> Activity 6: Group_by</a></li>
<li class="chapter" data-level="6.7" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-7-data-visualisation"><i class="fa fa-check"></i><b>6.7</b> Activity 7: Data visualisation</a></li>
<li class="chapter" data-level="6.8" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-8-make-r-your-own"><i class="fa fa-check"></i><b>6.8</b> Activity 8: Make R your own</a></li>
<li class="chapter" data-level="6.9" data-path="ref1.html"><a href="ref1.html#finished"><i class="fa fa-check"></i><b>6.9</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html"><i class="fa fa-check"></i><b>7</b> Intro to Data Viz</a><ul>
<li class="chapter" data-level="7.1" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-1-dplyr-recap"><i class="fa fa-check"></i><b>7.1</b> Activity 1: dplyr recap</a><ul>
<li class="chapter" data-level="7.1.1" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#data-visualisation"><i class="fa fa-check"></i><b>7.1.1</b> Data visualisation</a></li>
<li class="chapter" data-level="7.1.2" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-2-set-up"><i class="fa fa-check"></i><b>7.1.2</b> Activity 2: Set-up</a></li>
<li class="chapter" data-level="7.1.3" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-3-factors"><i class="fa fa-check"></i><b>7.1.3</b> Activity 3: Factors</a></li>
<li class="chapter" data-level="7.1.4" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-4-bar-plot"><i class="fa fa-check"></i><b>7.1.4</b> Activity 4: Bar plot</a></li>
<li class="chapter" data-level="7.1.5" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-5-violin-boxplot"><i class="fa fa-check"></i><b>7.1.5</b> Activity 5: Violin-boxplot</a></li>
<li class="chapter" data-level="7.1.6" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-6-layers-part-2"><i class="fa fa-check"></i><b>7.1.6</b> Activity 6: Layers part 2</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="scatterplots.html"><a href="scatterplots.html"><i class="fa fa-check"></i><b>8</b> Scatterplots</a><ul>
<li class="chapter" data-level="8.0.1" data-path="loading-data.html"><a href="loading-data.html#activity-1-set-up"><i class="fa fa-check"></i><b>8.0.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="8.0.2" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-2-select"><i class="fa fa-check"></i><b>8.0.2</b> Activity 2: Select</a></li>
<li class="chapter" data-level="8.0.3" data-path="data-wrangling-2.html"><a href="data-wrangling-2.html#activity-3-arrange"><i class="fa fa-check"></i><b>8.0.3</b> Activity 3: Arrange</a></li>
<li class="chapter" data-level="8.0.4" data-path="scatterplots.html"><a href="scatterplots.html#activity-4filter"><i class="fa fa-check"></i><b>8.0.4</b> Activity 4:Filter</a></li>
<li class="chapter" data-level="8.0.5" data-path="scatterplots.html"><a href="scatterplots.html#activity-5-group-and-summarise"><i class="fa fa-check"></i><b>8.0.5</b> Activity 5: Group and summarise</a></li>
<li class="chapter" data-level="8.0.6" data-path="scatterplots.html"><a href="scatterplots.html#activity-6-mutate"><i class="fa fa-check"></i><b>8.0.6</b> Activity 6: Mutate</a></li>
<li class="chapter" data-level="8.0.7" data-path="scatterplots.html"><a href="scatterplots.html#activity-7-scatterplots"><i class="fa fa-check"></i><b>8.0.7</b> Activity 7: Scatterplots</a></li>
<li class="chapter" data-level="8.0.8" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>8.0.8</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html"><i class="fa fa-check"></i><b>9</b> AQ data and recap</a><ul>
<li class="chapter" data-level="9.0.1" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#autism-quotient-data"><i class="fa fa-check"></i><b>9.0.1</b> Autism-quotient data</a></li>
<li class="chapter" data-level="9.0.2" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-1-download-the-data"><i class="fa fa-check"></i><b>9.0.2</b> Activity 1: Download the data</a></li>
<li class="chapter" data-level="9.0.3" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-2-open-a-new-markdown-document"><i class="fa fa-check"></i><b>9.0.3</b> Activity 2: Open a new Markdown document</a></li>
<li class="chapter" data-level="9.0.4" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-3-create-a-new-code-chunk"><i class="fa fa-check"></i><b>9.0.4</b> Activity 3: Create a new code chunk</a></li>
<li class="chapter" data-level="9.0.5" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-4-load-in-the-data"><i class="fa fa-check"></i><b>9.0.5</b> Activity 4: Load in the data</a></li>
<li class="chapter" data-level="9.0.6" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-5-look-at-the-data"><i class="fa fa-check"></i><b>9.0.6</b> Activity 5: Look at the data</a></li>
<li class="chapter" data-level="9.0.7" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#thinking-through-the-problem"><i class="fa fa-check"></i><b>9.0.7</b> Thinking through the problem</a></li>
<li class="chapter" data-level="9.0.8" data-path="aq-data-and-recap.html"><a href="aq-data-and-recap.html#activity-5-recap"><i class="fa fa-check"></i><b>9.0.8</b> Activity 5: Recap</a></li>
<li class="chapter" data-level="9.0.9" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>9.0.9</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="reshaping-data.html"><a href="reshaping-data.html"><i class="fa fa-check"></i><b>10</b> Reshaping data</a><ul>
<li class="chapter" data-level="10.0.1" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-1-load-in-the-data"><i class="fa fa-check"></i><b>10.0.1</b> Activity 1: Load in the data</a></li>
<li class="chapter" data-level="10.0.2" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-2-pivot_longer"><i class="fa fa-check"></i><b>10.0.2</b> Activity 2: <code>pivot_longer()</code></a></li>
<li class="chapter" data-level="10.0.3" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-3-filter"><i class="fa fa-check"></i><b>10.0.3</b> Activity 3: <code>filter()</code></a></li>
<li class="chapter" data-level="10.0.4" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-4-inner_join"><i class="fa fa-check"></i><b>10.0.4</b> Activity 4: <code>inner_join()</code></a></li>
<li class="chapter" data-level="10.0.5" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-5-another-inner_join"><i class="fa fa-check"></i><b>10.0.5</b> Activity 5: Another <code>inner_join()</code></a></li>
<li class="chapter" data-level="10.0.6" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-6-calculating-the-aq-score"><i class="fa fa-check"></i><b>10.0.6</b> Activity 6: Calculating the AQ score</a></li>
<li class="chapter" data-level="10.0.7" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-7-calculating-all-scores"><i class="fa fa-check"></i><b>10.0.7</b> Activity 7: Calculating all scores</a></li>
<li class="chapter" data-level="10.0.8" data-path="reshaping-data.html"><a href="reshaping-data.html#activity-8-visualisation"><i class="fa fa-check"></i><b>10.0.8</b> Activity 8: Visualisation</a></li>
<li class="chapter" data-level="10.0.9" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>10.0.9</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="pipes.html"><a href="pipes.html"><i class="fa fa-check"></i><b>11</b> Pipes</a><ul>
<li class="chapter" data-level="11.0.1" data-path="pipes.html"><a href="pipes.html#activity-1-recap"><i class="fa fa-check"></i><b>11.0.1</b> Activity 1: Recap</a></li>
<li class="chapter" data-level="11.0.2" data-path="intro-to-data-viz.html"><a href="intro-to-data-viz.html#activity-2-set-up"><i class="fa fa-check"></i><b>11.0.2</b> Activity 2: Set-up</a></li>
<li class="chapter" data-level="11.0.3" data-path="pipes.html"><a href="pipes.html#activity-3-example-pipe-1"><i class="fa fa-check"></i><b>11.0.3</b> Activity 3: Example pipe 1</a></li>
<li class="chapter" data-level="11.0.4" data-path="pipes.html"><a href="pipes.html#activity-4-example-pipe-2"><i class="fa fa-check"></i><b>11.0.4</b> Activity 4: Example pipe 2</a></li>
<li class="chapter" data-level="11.0.5" data-path="pipes.html"><a href="pipes.html#activity-5-example-pipe-3"><i class="fa fa-check"></i><b>11.0.5</b> Activity 5: Example pipe 3</a></li>
<li class="chapter" data-level="11.0.6" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>11.0.6</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="mega-pipe.html"><a href="mega-pipe.html"><i class="fa fa-check"></i><b>12</b> Mega pipe</a><ul>
<li class="chapter" data-level="12.0.1" data-path="loading-data.html"><a href="loading-data.html#activity-1-set-up"><i class="fa fa-check"></i><b>12.0.1</b> Activity 1: Set-up</a></li>
<li class="chapter" data-level="12.0.2" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-2-mega-pipe"><i class="fa fa-check"></i><b>12.0.2</b> Activity 2: Mega pipe</a></li>
<li class="chapter" data-level="12.0.3" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-3-pipe-plot"><i class="fa fa-check"></i><b>12.0.3</b> Activity 3: Pipe plot</a></li>
<li class="chapter" data-level="12.0.4" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-4-aq-score-by-gender"><i class="fa fa-check"></i><b>12.0.4</b> Activity 4: AQ score by gender</a></li>
<li class="chapter" data-level="12.0.5" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-5-bad-bar-plots"><i class="fa fa-check"></i><b>12.0.5</b> Activity 5: Bad bar plots</a></li>
<li class="chapter" data-level="12.0.6" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-6-density-plots"><i class="fa fa-check"></i><b>12.0.6</b> Activity 6: Density plots</a></li>
<li class="chapter" data-level="12.0.7" data-path="mega-pipe.html"><a href="mega-pipe.html#activity-7-saving-plots"><i class="fa fa-check"></i><b>12.0.7</b> Activity 7: Saving plots</a></li>
<li class="chapter" data-level="12.0.8" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>12.0.8</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="intro-to-probability.html"><a href="intro-to-probability.html"><i class="fa fa-check"></i><b>13</b> Intro to Probability</a><ul>
<li class="chapter" data-level="13.0.1" data-path="intro-to-probability.html"><a href="intro-to-probability.html#activity-1-prep"><i class="fa fa-check"></i><b>13.0.1</b> Activity 1: Prep</a></li>
<li class="chapter" data-level="13.0.2" data-path="intro-to-probability.html"><a href="intro-to-probability.html#what-is-probability"><i class="fa fa-check"></i><b>13.0.2</b> What is probability?</a></li>
<li class="chapter" data-level="13.0.3" data-path="intro-to-probability.html"><a href="intro-to-probability.html#types-of-data"><i class="fa fa-check"></i><b>13.0.3</b> Types of data</a></li>
<li class="chapter" data-level="13.0.4" data-path="intro-to-probability.html"><a href="intro-to-probability.html#activity-2-types-of-data"><i class="fa fa-check"></i><b>13.0.4</b> Activity 2: Types of data</a></li>
<li class="chapter" data-level="13.0.5" data-path="intro-to-probability.html"><a href="intro-to-probability.html#probability-distributions"><i class="fa fa-check"></i><b>13.0.5</b> Probability distributions</a></li>
<li class="chapter" data-level="13.0.6" data-path="intro-to-probability.html"><a href="intro-to-probability.html#the-uniform-distribution"><i class="fa fa-check"></i><b>13.0.6</b> The uniform distribution</a></li>
<li class="chapter" data-level="13.0.7" data-path="intro-to-probability.html"><a href="intro-to-probability.html#the-binomial-distribution"><i class="fa fa-check"></i><b>13.0.7</b> The binomial distribution</a></li>
<li class="chapter" data-level="13.0.8" data-path="intro-to-probability.html"><a href="intro-to-probability.html#the-normal-distribution"><i class="fa fa-check"></i><b>13.0.8</b> The normal distribution</a></li>
<li class="chapter" data-level="13.0.9" data-path="intro-to-probability.html"><a href="intro-to-probability.html#activity-3-normal-distribution"><i class="fa fa-check"></i><b>13.0.9</b> Activity 3: Normal distribution</a></li>
<li class="chapter" data-level="13.0.10" data-path="intro-to-probability.html"><a href="intro-to-probability.html#activity-4-distribution-test"><i class="fa fa-check"></i><b>13.0.10</b> Activity 4: Distribution test</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="probability-continued.html"><a href="probability-continued.html"><i class="fa fa-check"></i><b>14</b> Probability continued</a><ul>
<li class="chapter" data-level="14.0.1" data-path="probability-continued.html"><a href="probability-continued.html#activity-2-dbinom"><i class="fa fa-check"></i><b>14.0.1</b> Activity 2: <code>dbinom()</code></a></li>
<li class="chapter" data-level="14.0.2" data-path="probability-continued.html"><a href="probability-continued.html#activity-3-pbinom"><i class="fa fa-check"></i><b>14.0.2</b> Activity 3: <code>pbinom()</code></a></li>
<li class="chapter" data-level="14.0.3" data-path="probability-continued.html"><a href="probability-continued.html#activity-4-pbinom-2"><i class="fa fa-check"></i><b>14.0.3</b> Activity 4: <code>pbinom()</code> 2</a></li>
<li class="chapter" data-level="14.0.4" data-path="probability-continued.html"><a href="probability-continued.html#activity-5-qbinom"><i class="fa fa-check"></i><b>14.0.4</b> Activity 5: <code>qbinom()</code></a></li>
<li class="chapter" data-level="14.0.5" data-path="probability-continued.html"><a href="probability-continued.html#normal-distribution"><i class="fa fa-check"></i><b>14.0.5</b> Normal distribution</a></li>
<li class="chapter" data-level="14.0.6" data-path="probability-continued.html"><a href="probability-continued.html#probability-of-heights"><i class="fa fa-check"></i><b>14.0.6</b> Probability of heights</a></li>
<li class="chapter" data-level="14.0.7" data-path="probability-continued.html"><a href="probability-continued.html#activity-6pnorm"><i class="fa fa-check"></i><b>14.0.7</b> Activity 6:<code>pnorm()</code></a></li>
<li class="chapter" data-level="14.0.8" data-path="probability-continued.html"><a href="probability-continued.html#activity-7-pnorm-2"><i class="fa fa-check"></i><b>14.0.8</b> Activity 7: <code>pnorm</code> 2</a></li>
<li class="chapter" data-level="14.0.9" data-path="probability-continued.html"><a href="probability-continued.html#activity-8-pnorm-3"><i class="fa fa-check"></i><b>14.0.9</b> Activity 8: <code>pnorm</code> 3</a></li>
<li class="chapter" data-level="14.0.10" data-path="probability-continued.html"><a href="probability-continued.html#activity-9-qnorm"><i class="fa fa-check"></i><b>14.0.10</b> Activity 9: <code>qnorm()</code></a></li>
<li class="chapter" data-level="14.0.11" data-path="scatterplots.html"><a href="scatterplots.html#activity-solutions"><i class="fa fa-check"></i><b>14.0.11</b> Activity solutions</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="simulation.html"><a href="simulation.html"><i class="fa fa-check"></i><b>15</b> Simulation</a><ul>
<li class="chapter" data-level="15.0.1" data-path="simulation.html"><a href="simulation.html#simulation-1"><i class="fa fa-check"></i><b>15.0.1</b> Simulation</a></li>
<li class="chapter" data-level="15.0.2" data-path="simulation.html"><a href="simulation.html#activity-1-sample"><i class="fa fa-check"></i><b>15.0.2</b> Activity 1: <code>sample()</code></a></li>
<li class="chapter" data-level="15.0.3" data-path="simulation.html"><a href="simulation.html#activity-2-sum"><i class="fa fa-check"></i><b>15.0.3</b> Activity 2: <code>sum()</code></a></li>
<li class="chapter" data-level="15.0.4" data-path="simulation.html"><a href="simulation.html#activity-3-replicate-1"><i class="fa fa-check"></i><b>15.0.4</b> Activity 3: <code>replicate()</code> 1</a></li>
<li class="chapter" data-level="15.0.5" data-path="simulation.html"><a href="simulation.html#monte-carlo-simulation"><i class="fa fa-check"></i><b>15.0.5</b> Monte Carlo simulation</a></li>
<li class="chapter" data-level="15.0.6" data-path="simulation.html"><a href="simulation.html#activity-4-replicate-2"><i class="fa fa-check"></i><b>15.0.6</b> Activity 4: <code>replicate()</code> 2</a></li>
<li class="chapter" data-level="15.0.7" data-path="simulation.html"><a href="simulation.html#activity-5-probability"><i class="fa fa-check"></i><b>15.0.7</b> Activity 5: probability</a></li>
<li class="chapter" data-level="15.0.8" data-path="simulation.html"><a href="simulation.html#activity-6-visualisation"><i class="fa fa-check"></i><b>15.0.8</b> Activity 6: visualisation</a></li>
<li class="chapter" data-level="15.0.9" data-path="simulation.html"><a href="simulation.html#activity-7-big-data"><i class="fa fa-check"></i><b>15.0.9</b> Activity 7: big data</a></li>
<li class="chapter" data-level="15.0.10" data-path="simulation.html"><a href="simulation.html#activity-8-rnorm"><i class="fa fa-check"></i><b>15.0.10</b> Activity 8: <code>rnorm()</code></a></li>
<li class="chapter" data-level="15.0.11" data-path="simulation.html"><a href="simulation.html#activity-9-simulate-a-dataset"><i class="fa fa-check"></i><b>15.0.11</b> Activity 9: Simulate a dataset</a></li>
<li class="chapter" data-level="15.0.12" data-path="ref1.html"><a href="ref1.html#finished"><i class="fa fa-check"></i><b>15.0.12</b> Finished!</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="project-analysis.html"><a href="project-analysis.html"><i class="fa fa-check"></i><b>16</b> Project analysis</a><ul>
<li class="chapter" data-level="16.0.1" data-path="project-analysis.html"><a href="project-analysis.html#step-1-load-in-packages-and-data"><i class="fa fa-check"></i><b>16.0.1</b> Step 1: Load in packages and data</a></li>
<li class="chapter" data-level="16.0.2" data-path="project-analysis.html"><a href="project-analysis.html#step-2-clean-up-the-data"><i class="fa fa-check"></i><b>16.0.2</b> Step 2: Clean up the data</a></li>
<li class="chapter" data-level="16.0.3" data-path="project-analysis.html"><a href="project-analysis.html#step-3-join"><i class="fa fa-check"></i><b>16.0.3</b> Step 3: Join</a></li>
<li class="chapter" data-level="16.0.4" data-path="project-analysis.html"><a href="project-analysis.html#step-4.-select-your-variables"><i class="fa fa-check"></i><b>16.0.4</b> Step 4. Select your variables</a></li>
<li class="chapter" data-level="16.0.5" data-path="project-analysis.html"><a href="project-analysis.html#step-5-factors"><i class="fa fa-check"></i><b>16.0.5</b> Step 5: Factors</a></li>
<li class="chapter" data-level="16.0.6" data-path="project-analysis.html"><a href="project-analysis.html#step-6-filter"><i class="fa fa-check"></i><b>16.0.6</b> Step 6: Filter</a></li>
<li class="chapter" data-level="16.0.7" data-path="project-analysis.html"><a href="project-analysis.html#step-7-sub-scale-scores"><i class="fa fa-check"></i><b>16.0.7</b> Step 7: Sub-scale scores</a></li>
<li class="chapter" data-level="16.0.8" data-path="project-analysis.html"><a href="project-analysis.html#step-8-split-the-dataset"><i class="fa fa-check"></i><b>16.0.8</b> Step 8: Split the dataset</a></li>
<li class="chapter" data-level="16.0.9" data-path="project-analysis.html"><a href="project-analysis.html#step-9-demoraphic-information"><i class="fa fa-check"></i><b>16.0.9</b> Step 9: Demoraphic information</a></li>
<li class="chapter" data-level="16.0.10" data-path="project-analysis.html"><a href="project-analysis.html#step-10-descriptive-statistics"><i class="fa fa-check"></i><b>16.0.10</b> Step 10: Descriptive statistics</a></li>
<li class="chapter" data-level="16.0.11" data-path="project-analysis.html"><a href="project-analysis.html#step-11-visualisation"><i class="fa fa-check"></i><b>16.0.11</b> Step 11: visualisation</a></li>
</ul></li>
<li class="appendix"><span><b>Appendices</b></span></li>
<li class="chapter" data-level="A" data-path="exporting-files-from-the-server.html"><a href="exporting-files-from-the-server.html"><i class="fa fa-check"></i><b>A</b> Exporting files from the server</a></li>
<li class="chapter" data-level="B" data-path="programming-basics.html"><a href="programming-basics.html#installing-r-on-your-computer"><i class="fa fa-check"></i><b>B</b> Installing R on your computer</a><ul>
<li class="chapter" data-level="B.1" data-path="installing-r-on-your-computer.html"><a href="installing-r-on-your-computer.html"><i class="fa fa-check"></i><b>B.1</b> Why should I install R on my computer?</a></li>
<li class="chapter" data-level="B.2" data-path="installing-r-on-your-computer.html"><a href="installing-r-on-your-computer.html#windows"><i class="fa fa-check"></i><b>B.2</b> Windows</a></li>
<li class="chapter" data-level="B.3" data-path="installing-r-on-your-computer.html"><a href="installing-r-on-your-computer.html#mac"><i class="fa fa-check"></i><b>B.3</b> Mac</a></li>
<li class="chapter" data-level="B.4" data-path="installing-r-on-your-computer.html"><a href="installing-r-on-your-computer.html#chromebooks"><i class="fa fa-check"></i><b>B.4</b> Chromebooks</a></li>
</ul></li>
<li class="divider"></li>
<li><a rel="license" href="https://creativecommons.org/licenses/by-sa/4.0/" 
    target="blank"><img alt="Creative Commons License" 
    style="border-width:0" 
    src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" /></a><li>
<li><a href="https://psyteachr.github.io/books" target="blank">PsyTeachR Books</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Level 1 Data Skills</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="data-wrangling-1" class="section level1">
<h1><span class="header-section-number">5</span> Data wrangling 1</h1>
<div class="info">
<p>
So far you have been introduced to the R environment (e.g. setting your working directory and the difference between .R and .Rmd files). You also began working with messy data by having a go at loading in datasets using <code>read_csv()</code>, joined files together using <code>inner_join()</code>, and pulled out variables of interest using <code>select()</code>.
</p>
<p>
In this chapter, we’ll be moving on to becoming familiar with the Wickham Six and the functionality of the R package, <code>tidyverse</code>!
</p>
</div>
<p>Data comes in lots of different formats. One of the most common formats is that of a two-dimensional table (the two dimensions being rows and columns). Usually, each row stands for a separate observation (e.g. a subject), and each column stands for a different variable (e.g. a response, category, or group). A key benefit of tabular data (i.e., data in a table) is that it allows you to store different types of data-numerical measurements, alphanumeric labels, categorical descriptors-all in one place.</p>
<p>It may surprise you to learn that scientists actually spend far more time cleaning and preparing their data than they spend actually analysing it. This means completing tasks such as cleaning up bad values, changing the structure of tables, merging information stored in separate tables, reducing the data down to a subset of observations, and producing data summaries. Some have estimated that up to 80% of time spent on data analysis involves such data preparation tasks (Dasu &amp; Johnson, 2003)!</p>
<p>Many people seem to operate under the assumption that the only option for data cleaning is the painstaking and time-consuming cutting and pasting of data within a spreadsheet program like Excel. We have witnessed students and colleagues waste days, weeks, and even months manually transforming their data in Excel, cutting, copying, and pasting data. Fixing up your data by hand is not only a terrible use of your time, but it is error-prone and not reproducible. Additionally, in this age where we can easily collect massive datasets online, you will not be able to organise, clean, and prepare these by hand.</p>
<p>In short, you will not thrive as a psychologist if you do not learn some key data wrangling skills. Although every dataset presents unique challenges, there are some systematic principles you should follow that will make your analyses easier, less error-prone, more efficient, and more reproducible.</p>
<p>In this chapter you will see how data science skills will allow you to efficiently get answers to nearly any question you might want to ask about your data. By learning how to properly make your computer do the hard and boring work for you, you can focus on the bigger issues.</p>
<div id="tidyverse" class="section level2">
<h2><span class="header-section-number">5.1</span> Tidyverse</h2>
<p>Tidyverse (<a href="https://www.tidyverse.org/" class="uri">https://www.tidyverse.org/</a>) is a collection of R packages created by world-famous data scientist Hadley Wickham.</p>
<p>Tidyverse contains six core packages: <code>dplyr</code>, <code>tidyr</code>, <code>readr</code>, <code>purrr</code>, <code>ggplot2</code>, and <code>tibble</code>. In the last chapter when you typed <code>library(tidyverse)</code> into R, you will have seen that it loads in all of these packages in one go. Within these six core packages, you should be able to find everything you need to wrangle and visualise your data.</p>
<p>In this chapter, we are going to focus on the <code>dplyr</code> package, which contains six important functions:</p>
<ul>
<li><code>select()</code> Include or exclude certain variables (columns)</li>
<li><code>filter()</code> Include or exclude certain observations (rows)</li>
<li><code>mutate()</code> Create new variables (columns)</li>
<li><code>arrange()</code> Change the order of observations (rows)</li>
<li><code>group_by()</code> Organize the observations into groups</li>
<li><code>summarise()</code> Derive aggregate variables for groups of observations</li>
</ul>
<p>These six functions are known as ’single table verbs’ because they only operate on one table at a time. Although the operations of these functions may seem very simplistic, it’s amazing what you can accomplish when you string them together: Hadley Wickham has claimed that 90% of data analysis can be reduced to the operations described by these six functions.</p>
<p>Again, we don’t expect you to remember everything in this chapter - the important thing is that you know where to come and look for help when you need to do particular tasks. Being good at coding really is just being good at knowing what to copy and paste.</p>
</div>
<div id="the-babynames-database" class="section level2">
<h2><span class="header-section-number">5.2</span> The <code>babynames</code> database</h2>
<p>To demonstrate the power of the six <code>dplyr</code> verbs, we will use them to work with the babynames data from the <code>babynames</code> package (we will return to the AHI and CES-D dataset in the next chapter!). The babynames dataset has historical information about births of babies in the U.S.</p>
</div>
<div id="activity-1-set-up" class="section level2">
<h2><span class="header-section-number">5.3</span> Activity 1: Set-up</h2>
<p>Do the following. If you need help, consult Programming Basics and Intro to R.</p>
<ul>
<li>Open R Studio and ensure the environment is clear.<br />
</li>
<li>Open the <code>stub-wrangling-1.Rmd</code> file and ensure that the working directory is set to your Data Skills folder.<br />
</li>
<li>If you’re on the server, avoid a number of issues by restarting the session - click <code>Session</code> - <code>Restart R</code><br />
</li>
<li>If you are working on your own computer, install the package <code>babynames</code>. If you are working on the server or a university computer, this package will already be installed.</li>
<li>Type and run the code that loads the packages <code>tidyverse</code> and <code>babynames</code> using <code>library()</code> in the Activity 1 code chunk.</li>
</ul>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="data-wrangling-1.html#cb28-1"></a><span class="kw">library</span>(tidyverse)</span>
<span id="cb28-2"><a href="data-wrangling-1.html#cb28-2"></a><span class="kw">library</span>(babynames)</span></code></pre></div>
</div>
<div id="activity-2-look-at-the-data" class="section level2">
<h2><span class="header-section-number">5.4</span> Activity 2: Look at the data</h2>
<p>The package <code>babynames</code> contains an object of the same name that contains all the data about babynames.</p>
<ul>
<li>View a preview of this dataset by typing <code>babynames</code> in to the console. You should see the following output:</li>
</ul>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="data-wrangling-1.html#cb29-1"></a>babynames</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724
##  2  1880 F     Anna       2604 0.0267
##  3  1880 F     Emma       2003 0.0205
##  4  1880 F     Elizabeth  1939 0.0199
##  5  1880 F     Minnie     1746 0.0179
##  6  1880 F     Margaret   1578 0.0162
##  7  1880 F     Ida        1472 0.0151
##  8  1880 F     Alice      1414 0.0145
##  9  1880 F     Bertha     1320 0.0135
## 10  1880 F     Sarah      1288 0.0132
## # ... with 1,924,655 more rows</code></pre>
<p>The first line tells us that the object we are looking at is in a <code>tibble</code> with information on five variables with over 1.9 million rows. Yes, this dataset contains 1.8 <strong>million</strong> observations. Interested in analyzing these data by hand? No thanks! A tibble is basically a table of data presenting a two dimensional array of your data.</p>
<p>Each row in the table represents data about births for a given name and sex in a given year. The variables are:</p>
<table>
<thead>
<tr class="header">
<th>variable</th>
<th>type</th>
<th>description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>year</td>
<td>double (numeric)</td>
<td>year of birth</td>
</tr>
<tr class="even">
<td>sex |</td>
<td>character |rec</td>
<td>recorded sex of baby (F = female, M = male)</td>
</tr>
<tr class="odd">
<td>name</td>
<td>character |for</td>
<td>forename given to baby</td>
</tr>
<tr class="even">
<td>n |in</td>
<td>integer |num</td>
<td>number of babies given that name</td>
</tr>
<tr class="odd">
<td>prop</td>
<td>double (numeric)</td>
<td>proportion of all babies of that sex</td>
</tr>
</tbody>
</table>
<p>The first row of the table tells us that in the year 1880, there were 7065 baby girls born in the U.S. who were given the name Mary, and this accounted for about 7% of all baby girls.</p>
</div>
<div id="activity-3-data-visualisation" class="section level2">
<h2><span class="header-section-number">5.5</span> Activity 3: Data visualisation</h2>
<ul>
<li>Type the code below into a new code chunk and run it.</li>
</ul>
<p>We’re going to cover how to write visualisation code in the next chapter so still don’t worry about not understanding the plot code yet. The point is show you how much you can accomplish with very little code. The code creates a graph showing the popularity of four girl baby names - Alexandra, Beverly, Emily, and Kathleen - from 1880 to 2014. You should see Figure <a href="data-wrangling-1.html#fig:babynames-plot">5.1</a> appear, which shows the proportion of each name across different years.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="data-wrangling-1.html#cb31-1"></a>dat &lt;-<span class="st"> </span>babynames <span class="op">%&gt;%</span><span class="st"> </span></span>
<span id="cb31-2"><a href="data-wrangling-1.html#cb31-2"></a><span class="st">  </span><span class="kw">filter</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Emily&quot;</span>,<span class="st">&quot;Kathleen&quot;</span>,<span class="st">&quot;Alexandra&quot;</span>,<span class="st">&quot;Beverly&quot;</span>), sex<span class="op">==</span><span class="st">&quot;F&quot;</span>)</span>
<span id="cb31-3"><a href="data-wrangling-1.html#cb31-3"></a></span>
<span id="cb31-4"><a href="data-wrangling-1.html#cb31-4"></a><span class="kw">ggplot</span>(<span class="dt">data =</span> dat,<span class="kw">aes</span>(<span class="dt">x =</span> year,<span class="dt">y =</span> prop, <span class="dt">colour=</span>name))<span class="op">+</span></span>
<span id="cb31-5"><a href="data-wrangling-1.html#cb31-5"></a><span class="st">  </span><span class="kw">geom_line</span>()  </span></code></pre></div>
<div class="figure" style="text-align: center"><span id="fig:babynames-plot"></span>
<img src="05-wrangling-1_files/figure-html/babynames-plot-1.png" alt="Proportion of four baby names from 1880 to 2014" width="100%" />
<p class="caption">
Figure 5.1: Proportion of four baby names from 1880 to 2014
</p>
</div>
<ul>
<li>Change the names to your own examples and see how the plot changes. You can also change the sex from “F” to “M”. Post the photos of your new plots on the Teams Data Skills channel.</li>
<li>Because in most countries assigned sex at birth is binary, there is no data on intersex, trans or non-binary names. In lieu of that, here’s the <a href="https://en.wikipedia.org/wiki/Unisex_name">Wikipedia page about gender-neutral names and naming laws</a> around the world which will hopefully make you question why on earth we ascribe someone’s entire gender identity to a bunch of sounds and letters we use to label them.</li>
</ul>
</div>
<div id="activity-4-selecting-variables-of-interest" class="section level2">
<h2><span class="header-section-number">5.6</span> Activity 4: Selecting variables of interest</h2>
<p>There are two numeric measurements of name popularity, <code>prop</code> (the proportion of all babies with each name) is probably more useful than <code>n</code> (total number of babies with that name), because it takes into account that different numbers of babies are born in different years.</p>
<p>Just like in Loading Data, if we wanted to create a dataset that only includes certain variables, we can use the <code>select()</code> function from the <code>dplyr</code> package. Run the below code to only select the columns <code>year</code>, <code>sex</code>, <code>name</code> and <code>prop</code>.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="data-wrangling-1.html#cb32-1"></a><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="co"># the object you want to select variables from</span></span>
<span id="cb32-2"><a href="data-wrangling-1.html#cb32-2"></a>       year, sex, name, prop) <span class="co"># the variables you want to select</span></span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 4
##     year sex   name        prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1  1880 F     Mary      0.0724
##  2  1880 F     Anna      0.0267
##  3  1880 F     Emma      0.0205
##  4  1880 F     Elizabeth 0.0199
##  5  1880 F     Minnie    0.0179
##  6  1880 F     Margaret  0.0162
##  7  1880 F     Ida       0.0151
##  8  1880 F     Alice     0.0145
##  9  1880 F     Bertha    0.0135
## 10  1880 F     Sarah     0.0132
## # ... with 1,924,655 more rows</code></pre>
<div class="danger">
<p>
If you get an error message when using select that says <code>unused argument</code> it means that it is trying to use the wrong version of the select function. There are two solutions to this, first, save you work and then restart the R session (click session -restart R) and then run all your code above again from the start, or replace <code>select</code> with <code>dplyr::select</code> which tells R exactly which version of the select function to use. We’d recommend restarting the session because this will get you in the habit and it’s a useful thing to try for a range of problems
</p>
</div>
<p>Alternatively, you can also tell R which variables you don’t want, in this case, rather than telling R to select <code>year</code>, <code>sex</code>, <code>name</code> and <code>prop</code>, we can simply tell it to drop the column <code>n</code> using the minus sign <code>-</code> before the variable name.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="data-wrangling-1.html#cb34-1"></a><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="op">-</span>n)</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 4
##     year sex   name        prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      &lt;dbl&gt;
##  1  1880 F     Mary      0.0724
##  2  1880 F     Anna      0.0267
##  3  1880 F     Emma      0.0205
##  4  1880 F     Elizabeth 0.0199
##  5  1880 F     Minnie    0.0179
##  6  1880 F     Margaret  0.0162
##  7  1880 F     Ida       0.0151
##  8  1880 F     Alice     0.0145
##  9  1880 F     Bertha    0.0135
## 10  1880 F     Sarah     0.0132
## # ... with 1,924,655 more rows</code></pre>
<p>Note that <code>select()</code> does not change the original tibble, but makes a new tibble with the specified columns. If you don’t save this new tibble to an object, it won’t be saved. If you want to keep this new dataset, create a new object. When you run this code, you will see your new tibble appear in the environment pane.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="data-wrangling-1.html#cb36-1"></a>new_dat &lt;-<span class="st"> </span><span class="kw">select</span>(<span class="dt">.data =</span> babynames, <span class="op">-</span>n)</span></code></pre></div>
</div>
<div id="activity-5-arranging-the-data" class="section level2">
<h2><span class="header-section-number">5.7</span> Activity 5: Arranging the data</h2>
<p>The function <code>arrange()</code> will sort the rows in the table according to the columns you supply. Try running the following code:</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="data-wrangling-1.html#cb37-1"></a><span class="kw">arrange</span>(<span class="dt">.data =</span> babynames, <span class="co"># the data you want to sort</span></span>
<span id="cb37-2"><a href="data-wrangling-1.html#cb37-2"></a>        name) <span class="co"># the variable you want to sort by</span></span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name      n       prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;      &lt;dbl&gt;
##  1  2007 M     Aaban     5 0.00000226
##  2  2009 M     Aaban     6 0.00000283
##  3  2010 M     Aaban     9 0.00000439
##  4  2011 M     Aaban    11 0.00000542
##  5  2012 M     Aaban    11 0.00000543
##  6  2013 M     Aaban    14 0.00000694
##  7  2014 M     Aaban    16 0.00000783
##  8  2015 M     Aaban    15 0.00000736
##  9  2016 M     Aaban     9 0.00000446
## 10  2017 M     Aaban    11 0.0000056 
## # ... with 1,924,655 more rows</code></pre>
<p>The data are now sorted in ascending alphabetical order by name. The default is to sort in ascending order. If you want it descending, wrap the name of the variable in the <code>desc()</code> function. For instance, to sort by year in descending order, run the following code:</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="data-wrangling-1.html#cb39-1"></a><span class="kw">arrange</span>(babynames,<span class="kw">desc</span>(year)) </span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 5
##     year sex   name          n    prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;   &lt;dbl&gt;
##  1  2017 F     Emma      19738 0.0105 
##  2  2017 F     Olivia    18632 0.00994
##  3  2017 F     Ava       15902 0.00848
##  4  2017 F     Isabella  15100 0.00805
##  5  2017 F     Sophia    14831 0.00791
##  6  2017 F     Mia       13437 0.00717
##  7  2017 F     Charlotte 12893 0.00688
##  8  2017 F     Amelia    11800 0.00629
##  9  2017 F     Evelyn    10675 0.00569
## 10  2017 F     Abigail   10551 0.00563
## # ... with 1,924,655 more rows</code></pre>
<p>You can also sort by more than one column. What do you think the following code will do?</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="data-wrangling-1.html#cb41-1"></a><span class="kw">arrange</span>(babynames, <span class="kw">desc</span>(year), <span class="kw">desc</span>(sex), <span class="kw">desc</span>(prop)) </span></code></pre></div>
</div>
<div id="activity-6-using-filter-to-select-observations" class="section level2">
<h2><span class="header-section-number">5.8</span> Activity 6: Using filter to select observations</h2>
<p>We have previously used <code>select()</code> to select certain variables or columns, however, frequently you will also want to select only certain observations or rows, for example, only babies born after 1999, or only babies named “Mary”. You do this using the verb <code>filter()</code>. The <code>filter()</code> function is a bit more involved than the other verbs, and requires more detailed explanation, but this is because it is also extremely powerful.</p>
<p>Here is an example of filter, can you guess what it will do?</p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="data-wrangling-1.html#cb42-1"></a> <span class="kw">filter</span>(<span class="dt">.data =</span> babynames, year <span class="op">&gt;</span><span class="st"> </span><span class="dv">2000</span>)</span></code></pre></div>
<p>The first part of the code tells the function to use the object <code>babynames</code>. The second argument, <code>year &gt; 2000</code>, is what is known as a <strong>Boolean expression</strong>: an expression whose evaluation results in a value of TRUE or FALSE. What <code>filter()</code> does is include any observations (rows) for which the expression evaluates to TRUE, and exclude any for which it evaluates to FALSE. So in effect, behind the scenes, <code>filter()</code> goes through the entire set of 1.8 million observations, row by row, checking the value of year for each row, keeping it if the value is greater than 2000, and rejecting it if it is less than 2000. To see how a boolean expression works, consider the code below:</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="data-wrangling-1.html#cb43-1"></a>years &lt;-<span class="st"> </span><span class="dv">1996</span><span class="op">:</span><span class="dv">2005</span></span>
<span id="cb43-2"><a href="data-wrangling-1.html#cb43-2"></a>years</span>
<span id="cb43-3"><a href="data-wrangling-1.html#cb43-3"></a>years <span class="op">&gt;</span><span class="st"> </span><span class="dv">2000</span></span></code></pre></div>
<pre><code>##  [1] 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
##  [1] FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
<p>You can see that the expression <code>years &gt; 2000</code> returns a <strong>logical vector</strong> (a vector of TRUE and FALSE values), where each element represents whether the expression is true or false for that element. For the first five elements (1996 to 2000) it is false, and for the last five elements (2001 to 2005) it is true.</p>
<p>Here are the most commonly used Boolean expressions.</p>
<table>
<thead>
<tr class="header">
<th>Operator |Name</th>
<th>Name |i</th>
<th>is TRUE if and only if</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A &lt; B |</td>
<td>less than |A</td>
<td>A is less than B</td>
</tr>
<tr class="even">
<td>A &lt;= B</td>
<td>less than or equal</td>
<td>A is less than or equal to B</td>
</tr>
<tr class="odd">
<td>A &gt; B |</td>
<td>greater than |A is g</td>
<td>A is greater than B</td>
</tr>
<tr class="even">
<td>A &gt;= B</td>
<td>greater than or equal</td>
<td>A is greater than or equal to B</td>
</tr>
<tr class="odd">
<td>A == B</td>
<td>equivalence</td>
<td>A exactly equals B</td>
</tr>
<tr class="even">
<td>A != B</td>
<td>not equal |A</td>
<td>A does not exactly equal B</td>
</tr>
<tr class="odd">
<td>A %in% B |in</td>
<td>in |A</td>
<td>A is an element of vector B</td>
</tr>
</tbody>
</table>
<p>If you want only those observations for a specific name (e.g., Mary), you use the equivalence operator <code>==</code>. Note that you use double equal signs, not a single equal sign.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="data-wrangling-1.html#cb45-1"></a><span class="kw">filter</span>(babynames, name <span class="op">==</span><span class="st"> &quot;Mary&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 268 x 5
##     year sex   name      n     prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt; &lt;int&gt;    &lt;dbl&gt;
##  1  1880 F     Mary   7065 0.0724  
##  2  1880 M     Mary     27 0.000228
##  3  1881 F     Mary   6919 0.0700  
##  4  1881 M     Mary     29 0.000268
##  5  1882 F     Mary   8148 0.0704  
##  6  1882 M     Mary     30 0.000246
##  7  1883 F     Mary   8012 0.0667  
##  8  1883 M     Mary     32 0.000284
##  9  1884 F     Mary   9217 0.0670  
## 10  1884 M     Mary     36 0.000293
## # ... with 258 more rows</code></pre>
<p>If you wanted all the names except Mary, you use the ‘not equals’ operator:</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="data-wrangling-1.html#cb47-1"></a><span class="kw">filter</span>(babynames, name<span class="op">!=</span><span class="st">&quot;Mary&quot;</span>) </span></code></pre></div>
<pre><code>## # A tibble: 1,924,397 x 5
##     year sex   name          n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Anna       2604 0.0267
##  2  1880 F     Emma       2003 0.0205
##  3  1880 F     Elizabeth  1939 0.0199
##  4  1880 F     Minnie     1746 0.0179
##  5  1880 F     Margaret   1578 0.0162
##  6  1880 F     Ida        1472 0.0151
##  7  1880 F     Alice      1414 0.0145
##  8  1880 F     Bertha     1320 0.0135
##  9  1880 F     Sarah      1288 0.0132
## 10  1880 F     Annie      1258 0.0129
## # ... with 1,924,387 more rows</code></pre>
<p>And if you wanted names from a defined set - e.g., names of British queens - you can use <code>%in%</code>:</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="data-wrangling-1.html#cb49-1"></a><span class="kw">filter</span>(babynames, name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Mary&quot;</span>,<span class="st">&quot;Elizabeth&quot;</span>,<span class="st">&quot;Victoria&quot;</span>))</span></code></pre></div>
<pre><code>## # A tibble: 772 x 5
##     year sex   name          n      prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;     &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724   
##  2  1880 F     Elizabeth  1939 0.0199   
##  3  1880 F     Victoria     93 0.000953 
##  4  1880 M     Mary         27 0.000228 
##  5  1880 M     Elizabeth     9 0.0000760
##  6  1881 F     Mary       6919 0.0700   
##  7  1881 F     Elizabeth  1852 0.0187   
##  8  1881 F     Victoria    117 0.00118  
##  9  1881 M     Mary         29 0.000268 
## 10  1882 F     Mary       8148 0.0704   
## # ... with 762 more rows</code></pre>
<p>This gives you data for the names in the vector on the right hand side of <code>%in%</code>. You can always invert an expression to get its opposite. So, for instance, if you instead wanted to get rid of all Marys, Elizabeths, and Victorias you would use the following:</p>
<div class="sourceCode" id="cb51"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb51-1"><a href="data-wrangling-1.html#cb51-1"></a><span class="kw">filter</span>(babynames, <span class="op">!</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Mary&quot;</span>,<span class="st">&quot;Elizabeth&quot;</span>,<span class="st">&quot;Victoria&quot;</span>)))</span></code></pre></div>
<pre><code>## # A tibble: 1,923,893 x 5
##     year sex   name         n   prop
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;    &lt;int&gt;  &lt;dbl&gt;
##  1  1880 F     Anna      2604 0.0267
##  2  1880 F     Emma      2003 0.0205
##  3  1880 F     Minnie    1746 0.0179
##  4  1880 F     Margaret  1578 0.0162
##  5  1880 F     Ida       1472 0.0151
##  6  1880 F     Alice     1414 0.0145
##  7  1880 F     Bertha    1320 0.0135
##  8  1880 F     Sarah     1288 0.0132
##  9  1880 F     Annie     1258 0.0129
## 10  1880 F     Clara     1226 0.0126
## # ... with 1,923,883 more rows</code></pre>
<p>You can include as many expressions as you like as additional arguments to <code>filter()</code> and it will only pull out the rows for which all of the expressions for that row evaluate to TRUE. For instance, <code>filter(babynames, year &gt; 2000, prop &gt; .01)</code> will pull out only those observations beyond the year 2000 that represent greater than 1% of the names for a given sex; any observation where either expression is false will be excluded. This ability to string together criteria makes <code>filter()</code> a very powerful member of the Wickham Six.</p>
<p><strong>Remember that this section exists. It will contain a lot of the answers to problems you face when wrangling data!</strong></p>
</div>
<div id="activity-7-creating-new-variables" class="section level2">
<h2><span class="header-section-number">5.9</span> Activity 7: Creating new variables</h2>
<p>Sometimes we need to create a new variable that doesn’t exist in our dataset. For instance, we might want to figure out what decade a particular year belongs to. To create new variables, we use the function <code>mutate()</code>. Note that if you want to save this new column, you need to save it to an object. Here, you are mutating a new column and attaching it to the <code>new_dat</code> object you created in Activity 4.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="data-wrangling-1.html#cb53-1"></a>new_dat &lt;-<span class="st"> </span><span class="kw">mutate</span>(<span class="dt">.data =</span> babynames, <span class="co"># the tibble you want to add a column to</span></span>
<span id="cb53-2"><a href="data-wrangling-1.html#cb53-2"></a>                  <span class="dt">decade =</span> <span class="kw">floor</span>(year<span class="op">/</span><span class="dv">10</span>) <span class="op">*</span><span class="dv">10</span>) <span class="co"># new column name = what you want it to contain</span></span>
<span id="cb53-3"><a href="data-wrangling-1.html#cb53-3"></a>new_dat</span></code></pre></div>
<pre><code>## # A tibble: 1,924,665 x 6
##     year sex   name          n   prop decade
##    &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;     &lt;int&gt;  &lt;dbl&gt;  &lt;dbl&gt;
##  1  1880 F     Mary       7065 0.0724   1880
##  2  1880 F     Anna       2604 0.0267   1880
##  3  1880 F     Emma       2003 0.0205   1880
##  4  1880 F     Elizabeth  1939 0.0199   1880
##  5  1880 F     Minnie     1746 0.0179   1880
##  6  1880 F     Margaret   1578 0.0162   1880
##  7  1880 F     Ida        1472 0.0151   1880
##  8  1880 F     Alice      1414 0.0145   1880
##  9  1880 F     Bertha     1320 0.0135   1880
## 10  1880 F     Sarah      1288 0.0132   1880
## # ... with 1,924,655 more rows</code></pre>
<p>In this case, you are creating a new column decade which has the decade each year appears in. This is calculated using the command <code>decade = floor(year/10)*10</code>.</p>
</div>
<div id="activity-8-grouping-and-summarising" class="section level2">
<h2><span class="header-section-number">5.10</span> Activity 8: Grouping and summarising</h2>
<p>Most quantitative analyses will require you to summarise your data somehow, for example, by calculating the mean, median or a sum total of your data. You can perform all of these operations using the function <code>summarise()</code>.</p>
<p>First, let’s use the object <code>dat</code> that just has the data for the four girls names, Alexandra, Beverly, Emily, and Kathleen. To start off, we’re simply going to calculate the total number of babies across all years that were given one of these four names.</p>
<p>It’s useful to get in the habit of translating your code into full sentences to make it easier to figure out what’s happening. You can read the below code as “run the function summarise using the data in the object <code>dat</code> to create a new variable named <code>total</code> that is the result of adding up all the numbers in the column <code>n</code>”.</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="data-wrangling-1.html#cb55-1"></a><span class="kw">summarise</span>(<span class="dt">.data =</span> dat, <span class="co"># the data you want to use</span></span>
<span id="cb55-2"><a href="data-wrangling-1.html#cb55-2"></a>          <span class="dt">total =</span> <span class="kw">sum</span>(n)) <span class="co"># result = operation</span></span></code></pre></div>
<pre><code>## # A tibble: 1 x 1
##     total
##     &lt;int&gt;
## 1 2161374</code></pre>
<p><code>summarise()</code> becomes even more powerful when combined with the final <code>dplyr</code> function, <code>group_by()</code>. Quite often, you will want to produce your summary statistics broken down by groups, for examples, the scores of participants in different conditions, or the reading time for native and non-native speakers.</p>
<p>There are two ways you can use <code>group_by()</code>. First, you can create a new, grouped object.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="data-wrangling-1.html#cb57-1"></a>group_dat &lt;-<span class="st"> </span><span class="kw">group_by</span>(<span class="dt">.data =</span> dat, <span class="co"># the data you want to group</span></span>
<span id="cb57-2"><a href="data-wrangling-1.html#cb57-2"></a>                      name) <span class="co"># the variable you want to group by</span></span></code></pre></div>
<p>If you look at this object in the viewer, it won’t look any different to the original <code>dat</code>, however, the underlying structure has changed. Let’s run the above summarise code again, but now using the grouped data.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="data-wrangling-1.html#cb58-1"></a><span class="kw">summarise</span>(<span class="dt">.data =</span> group_dat, </span>
<span id="cb58-2"><a href="data-wrangling-1.html#cb58-2"></a>          <span class="dt">total =</span> <span class="kw">sum</span>(n)) </span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 4 x 2
##   name       total
##   &lt;chr&gt;      &lt;int&gt;
## 1 Alexandra 231364
## 2 Beverly   376914
## 3 Emily     841491
## 4 Kathleen  711605</code></pre>
<p><code>summarise()</code> has performed exactly the same operation as before - adding up the total number in the column <code>n</code> - but this time it has done is separately for each group, which in this case was the variable <code>name</code>.</p>
<p>You can request multiple summary calculations to be performed in the same function. For example, the following code calculates the mean and median number of babies given each name every year.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="data-wrangling-1.html#cb61-1"></a><span class="kw">summarise</span>(group_dat,</span>
<span id="cb61-2"><a href="data-wrangling-1.html#cb61-2"></a>          <span class="dt">mean_year =</span> <span class="kw">mean</span>(n),</span>
<span id="cb61-3"><a href="data-wrangling-1.html#cb61-3"></a>          <span class="dt">median_year =</span> <span class="kw">median</span>(n))</span></code></pre></div>
<pre><code>## `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 4 x 3
##   name      mean_year median_year
##   &lt;chr&gt;         &lt;dbl&gt;       &lt;dbl&gt;
## 1 Alexandra     1977.        192 
## 2 Beverly       3089.        710.
## 3 Emily         6098.       1392.
## 4 Kathleen      5157.       3098</code></pre>
<p>You can also add multiple grouping variables. For example, the following code groups <code>new_dat</code> by <code>sex</code> and <code>decade</code> and then calculates the summary statistics to give us the mean and median number of male and female babies in each decade.</p>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="data-wrangling-1.html#cb64-1"></a>group_new_dat &lt;-<span class="st"> </span><span class="kw">group_by</span>(new_dat, sex, decade)</span>
<span id="cb64-2"><a href="data-wrangling-1.html#cb64-2"></a><span class="kw">summarise</span>(group_new_dat,</span>
<span id="cb64-3"><a href="data-wrangling-1.html#cb64-3"></a>          <span class="dt">mean_year =</span> <span class="kw">mean</span>(n),</span>
<span id="cb64-4"><a href="data-wrangling-1.html#cb64-4"></a>          <span class="dt">median_year =</span> <span class="kw">median</span>(n))</span></code></pre></div>
<pre><code>## `summarise()` regrouping output by &#39;sex&#39; (override with `.groups` argument)</code></pre>
<pre><code>## # A tibble: 28 x 4
## # Groups:   sex [2]
##    sex   decade mean_year median_year
##    &lt;chr&gt;  &lt;dbl&gt;     &lt;dbl&gt;       &lt;dbl&gt;
##  1 F       1880      111.          13
##  2 F       1890      128.          13
##  3 F       1900      131.          12
##  4 F       1910      187.          12
##  5 F       1920      211.          12
##  6 F       1930      214.          12
##  7 F       1940      262.          12
##  8 F       1950      288.          13
##  9 F       1960      235.          12
## 10 F       1970      147.          11
## # ... with 18 more rows</code></pre>
<div class="info">
<p>
If you get what looks like an error that says <code>summarise() ungrouping output (override with .groups argument)</code>don’t worry, this isn’t an error it’s just R telling you what it’s done. This message was included in a very recent update to the <code>tidyverse</code> which is why it doesn’t appear on some of the walkthrough vidoes.
</p>
</div>
</div>
<div id="activity-9-pipes" class="section level2">
<h2><span class="header-section-number">5.11</span> Activity 9: Pipes</h2>
<p>The final activity for this chapter essentially repeats what we’ve already covered but in a slightly different way. In the previous activities, you created new objects with new variables or groupings and then you called <code>summarise()</code> on those new objects in separate lines of code. As a result, you had multiple objects in your environment pane and you need to make sure that you keep track of the different names.</p>
<p>Instead, you can use <strong>pipes</strong>. Pipes are written as <code>%&gt;%</code>and they should be read as “and then”. Pipes allow you to string together ‘sentences’ of code into ‘paragraphs’ so that you don’t need to create intermediary objects. Again, it is easier to show than tell.</p>
<p>The below code does <strong>exactly</strong> the same as all the code we wrote above but it only creates one object.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="data-wrangling-1.html#cb67-1"></a>pipe_summary &lt;-<span class="st"> </span><span class="kw">mutate</span>(babynames, <span class="dt">decade =</span> <span class="kw">floor</span>(year<span class="op">/</span><span class="dv">10</span>) <span class="op">*</span><span class="dv">10</span>) <span class="op">%&gt;%</span></span>
<span id="cb67-2"><a href="data-wrangling-1.html#cb67-2"></a><span class="st">  </span><span class="kw">filter</span>(name <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;Emily&quot;</span>,<span class="st">&quot;Kathleen&quot;</span>,<span class="st">&quot;Alexandra&quot;</span>,<span class="st">&quot;Beverly&quot;</span>), sex<span class="op">==</span><span class="st">&quot;F&quot;</span>) <span class="op">%&gt;%</span></span>
<span id="cb67-3"><a href="data-wrangling-1.html#cb67-3"></a><span class="st">  </span><span class="kw">group_by</span>(name, decade) <span class="op">%&gt;%</span></span>
<span id="cb67-4"><a href="data-wrangling-1.html#cb67-4"></a><span class="st">  </span><span class="kw">summarise</span>(<span class="dt">mean_decade =</span> <span class="kw">mean</span>(n))</span></code></pre></div>
<p>The reason that this function is called a pipe is because it ‘pipes’ the data through to the next function. When you wrote the code previously, the first argument of each function was the dataset you wanted to work on. When you use pipes it will automatically take the data from the previous line of code so you don’t need to specify it again.</p>
<div class="try">
<p>
When learning to code it can be a useful practice to read your code ‘out loud’ in full sentences to help you understand what it is doing. You can read the code above as “create a new variable called decade AND THEN only keep the names Emily, Kathleen, Alexandra and Beverly that belong to female babies AND THEN group the dataset by name and decade AND THEN calculate the mean number of babies with each name per decade.” Try doing this each time you write a new bit of code.
</p>
</div>
<p>Some people find pipes a bit tricky to understand from a conceptual point of view, however, it’s well worth learning to use them as when your code starts getting longer they are much more efficient and mean you have to write less code which is always a good thing!</p>
</div>
<div id="finished" class="section level2">
<h2><span class="header-section-number">5.12</span> Finished!</h2>
<p>That was a long chapter but remember, you don’t need to memorise all of this code. You just need to know where to look for help. Finally, if you’re working from the R server, we’d recommend that you download a copy of the changes you’ve made to <code>stub-wrangling-1</code> so that you have a backup.</p>

</div>
</div>
<div class="psyteachr_footer">
  
</div>
<script>

/* update total correct if #total_correct exists */
update_total_correct = function() {
  if (t = document.getElementById("total_correct")) {
    t.innerHTML =
      document.getElementsByClassName("correct").length + " of " +
      document.getElementsByClassName("solveme").length + " correct";
  }
}

/* solution button toggling function */
b_func = function() {
  var cl = this.parentElement.classList;
  if (cl.contains('open')) {
    cl.remove("open");
  } else {
    cl.add("open");
  }
}

/* function for checking solveme answers */
solveme_func = function(e) {
  var real_answers = JSON.parse(this.dataset.answer);
  var my_answer = this.value;
  var cl = this.classList;
  if (cl.contains("ignorecase")) {
    my_answer = my_answer.toLowerCase();
  }
  if (cl.contains("nospaces")) {
    my_answer = my_answer.replace(/ /g, "");
  }
  
  if (my_answer !== "" & real_answers.includes(my_answer)) {
    cl.add("correct");
  } else {
    cl.remove("correct");
  }
  update_total_correct();
}

window.onload = function() {
  /* set up solution buttons */
  var buttons = document.getElementsByTagName("button");

  for (var i = 0; i < buttons.length; i++) {
    if (buttons[i].parentElement.classList.contains('solution')) {
      buttons[i].onclick = b_func;
    }
  }
  
  /* set up solveme inputs */
  var solveme = document.getElementsByClassName("solveme");

  for (var i = 0; i < solveme.length; i++) {
    /* make sure input boxes don't auto-anything */
    solveme[i].setAttribute("autocomplete","off");
    solveme[i].setAttribute("autocorrect", "off");
    solveme[i].setAttribute("autocapitalize", "off"); 
    solveme[i].setAttribute("spellcheck", "false");
    solveme[i].value = "";
    
    /* adjust answer for ignorecase or nospaces */
    var cl = solveme[i].classList;
    var real_answer = solveme[i].dataset.answer;
    if (cl.contains("ignorecase")) {
      real_answer = real_answer.toLowerCase();
    }
    if (cl.contains("nospaces")) {
      real_answer = real_answer.replace(/ /g, "");
    }
    solveme[i].dataset.answer = real_answer;
    
    /* attach checking function */
    solveme[i].onkeyup = solveme_func;
    solveme[i].onchange = solveme_func;
  }
  
  update_total_correct();
}

</script>
            </section>

          </div>
        </div>
      </div>
<a href="loading-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="data-wrangling-2.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"],
"google": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": {},
"toc": {
"collapse": "section",
"scroll_highlight": true
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
